"""empty message

Revision ID: 6ec62e60b14c
Revises: 7e7f9ee1a596
Create Date: 2024-01-10 11:18:12.097780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec62e60b14c'
down_revision = '7e7f9ee1a596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logged')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logged',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('data_logon', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='FK__logged__user_id__286302EC'),
    sa.PrimaryKeyConstraint('id', name='PK__logged__3213E83F8EF6D34E')
    )
    # ### end Alembic commands ###
